#121#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00005> <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/possibleDiseaseTarget> ?disease . 
?disease <http://www.w3.org/2002/07/owl#sameAs> ?other .
?other <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/sideEffectName> ?sideEffectName .
}


#122#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00131> <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/possibleDiseaseTarget> ?disease . 
?disease <http://www.w3.org/2002/07/owl#sameAs> ?other .
?other <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/sideEffectName> ?sideEffectName .
}


#123#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00665> <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/possibleDiseaseTarget> ?disease . 
?disease <http://www.w3.org/2002/07/owl#sameAs> ?other .
?other <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/sideEffectName> ?sideEffectName .
}


#124#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/dailymed/resource/drugs/1002> <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/possibleDiseaseTarget> ?disease . 
?disease <http://www.w3.org/2002/07/owl#sameAs> ?other .
?other <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/sideEffectName> ?sideEffectName .
}


#125#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/dailymed/resource/drugs/132> <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/possibleDiseaseTarget> ?disease . 
?disease <http://www.w3.org/2002/07/owl#sameAs> ?other .
?other <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/sideEffectName> ?sideEffectName .
}


#126#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/dailymed/resource/drugs/2643> <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/possibleDiseaseTarget> ?disease . 
?disease <http://www.w3.org/2002/07/owl#sameAs> ?other .
?other <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/sideEffectName> ?sideEffectName .
}


#127#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseases/3703> <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/possibleDrug> ?drug . 
?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/brandedDrug> ?branddug . 
?branddug  <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/activeMoiety> ?activeMoiety .
}


#128#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseases/0> <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/possibleDrug> ?drug . 
?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/brandedDrug> ?branddug . 
?branddug  <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/activeMoiety> ?activeMoiety .
}


#129#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseases/372> <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/possibleDrug> ?drug . 
?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/brandedDrug> ?branddug . 
?branddug  <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/activeMoiety> ?activeMoiety .
}


#130#
SELECT *
{ 
<http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseases/3703> <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/possibleDrug> ?drug . 
?drug <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/genericDrug> ?genericdrug . 
?genericdrug   <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/chebiId> ?chebiId .
}
